commerce/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls")),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

encyclopedia/urls.py
from django.urls import path

from . import views

app_name = 'ency'
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:entry>", views.entry, name="entry"),
    path("newPage", views.newPage, name="newPage"),
    path("updatePage/<str:title>", views.updatePage, name="updatePage")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from django.urls import reverse
from django import forms
from django.http import HttpResponseRedirect, HttpResponse
from random import choice
import re
from . import util
from markdown2 import Markdown


class searchForm(forms.Form):
    search = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Search'}))


class addNewEntry(forms.Form):
    title = forms.CharField(label="Entry Title")
    content = forms.CharField(widget=forms.Textarea(attrs={'rows': 50,
                                  'cols': 40,
                                  'style': 'height: 25em;' }))


def index(request):
    if request.method == "POST":
        form = searchForm(request.POST)
        if form.is_valid():
            search = form.cleaned_data['search']
            entries = util.list_entries()
            rgx = re.compile(f'^{search}+', re.IGNORECASE)
            ls = [rs for rs in entries if rgx.match(rs)]
            if len(ls) == 1 and search.lower() == ls[0].lower():
                return HttpResponseRedirect(reverse('ency:entry', args=[search]))
            else:
                return render(request, "encyclopedia/resultsPage.html", {
                    "entries": ls,
                    "form": searchForm()
                })
    else:
        return render(request, "encyclopedia/index.html", {
            "entries": util.list_entries(),
            "form": searchForm()
        })


def entry(request, entry):
    if entry == "random":
        entries = util.list_entries()
        random_entry = choice(entries)
        return HttpResponseRedirect(reverse('ency:entry', args=[random_entry]))
    elif request.method == 'POST':
        form = addNewEntry(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            content = form.cleaned_data['content']
            util.update_entry(title, content)
            return HttpResponseRedirect(reverse('ency:entry', args=[entry]))
    else:
        newEntry = util.get_entry(entry)
        markdowner = Markdown()
        return render(request, "encyclopedia/entry.html", {
            "entry": markdowner.convert(newEntry),
            "title": f"{entry}"
        })


def newPage(request):
    if request.method == 'POST':
        form = addNewEntry(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            content = form.cleaned_data['content']
            entry = util.save_entry(title, content)
            if entry == "ERROR":
                return HttpResponse("ERROR File already exist")
            else:
                return HttpResponseRedirect(reverse('ency:entry', args=[title]))
    else:
        return render(request, "encyclopedia/newPage.html", {
            "newEntry": addNewEntry()
        } )


def updatePage(request, title):
    content = util.get_entry(title)
    initial = {'title':f"{title}", 'content': f"{content}"}
    form = addNewEntry(initial=initial)
    return render(request, 'encyclopedia/updatePage.html', {
        'title': f"{title}",
        'update_form': form

    })
    

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block body %}
    {{entry | safe}}

    <form action="{% url 'ency:updatePage' title=title %}" method="post">
        {% csrf_token %}
        <input type="submit" value="update">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li> <a href="{% url 'ency:entry' entry=entry  %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'ency:index' %}" method="post">
                    {% csrf_token %}
                    {{form}}
                    <!-- <input class="search" type="text" name="q" placeholder="Search Encyclopedia"> -->
                </form>
                <div>
                    <a href="{% url 'ency:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'ency:newPage' %}"> Create New Page </a>
                </div>
                <div>
                    <a href="{% url 'ency:entry' entry='random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/newPage.html
{% extends "encyclopedia/layout.html" %}

{% block body %}
    <h3>Create a new entry</h3>
    <form action="{% url 'ency:newPage' %}" method="post">
        {% csrf_token %}
        {{ newEntry }}
        <input type="submit" value="Create">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/resultsPage.html
{% extends "encyclopedia/layout.html" %}

{% block body %}
    <h1>All Results</h1>

    <ul>
        {% for entry in entries %}
            <li> <a href="{% url 'ency:entry' entry=entry  %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/updatePage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block body %}

    <h3>Update Entry</h3>
     <form action="{% url 'ency:entry' entry=title %}" method="post">
        {{update_form}}
        {% csrf_token %}
        <input type="submit" value="Save Update">
    </form>

{% endblock %}